name: Bug report
description: Report a bug to help us improve
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: What happened?
      placeholder: A clear and concise description of the bug.
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: List the steps to reproduce the issue.
      placeholder: 1) ... 2) ...
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, Python version, Docker (if used), etc.
